# Generated by Django 4.1 on 2023-12-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, to='chores.usercomment'),
        ),
    ]
