# Generated by Django 4.1 on 2023-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('Done', 'Done')], default='todo', max_length=100),
        ),
    ]
