TASK_STATUS_DISPLAY_TODO = "To Do"
TASK_STATUS_DISPLAY_IN_PROGRESS = "In Progress"
TASK_STATUS_DISPLAY_ASSIGNED = "Assigned"
TASK_STATUS_DISPLAY_COMPLETED = "Completed"
TASK_STATUS_DISPLAY_UNDER_REVIEW = "Under Review"
TASK_STATUS_DISPLAY_DONE = "Done"

TASK_STATUS_TODO = "todo"
TASK_STATUS_IN_PROGRESS = "in_progress"
TASK_STATUS_ASSIGNED = "assigned"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_UNDER_REVIEW = "under_review"
TASK_STATUS_DONE = "Done"

TASK_STATUS_CHOICES = (
    (TASK_STATUS_TODO, TASK_STATUS_DISPLAY_TODO),
    (TASK_STATUS_IN_PROGRESS, TASK_STATUS_DISPLAY_IN_PROGRESS),
    (TASK_STATUS_ASSIGNED, TASK_STATUS_DISPLAY_ASSIGNED),
    (TASK_STATUS_COMPLETED, TASK_STATUS_DISPLAY_COMPLETED),
    (TASK_STATUS_UNDER_REVIEW, TASK_STATUS_DISPLAY_UNDER_REVIEW),
    (TASK_STATUS_DONE, TASK_STATUS_DISPLAY_DONE),
)
